import type {
  ActivityLog,
  CrmData,
  Lead,
  LeadAction,
  DocumentRecord,
  MarketAnalysisReport,
  MarketComparable,
  MarketListing,
  Notification,
  OfficeClient,
  PriceHistory,
  Property,
  Task,
  User,
} from "@/lib/types";
import { UNIT_GLOBAL_LOGO_DATA_URL } from "@/lib/client-assets";

export const users: User[] = [
  {
    id: "admin-1",
    name: "Mertcan Aslan",
    email: "mertcan@unitcrm.com",
    calendarEmail: "mertcan@unitcrm.com",
    role: "ADMIN",
    title: "Platform Admin",
    phone: "+90 532 000 10 01",
    avatarColor: "bg-slate-950",
    active: true,
  },
  {
    id: "manager-1",
    name: "Dorukhan Öründü",
    email: "dorukhan@unitglobal.com",
    calendarEmail: "dorukhan@unitglobal.com",
    role: "OFFICE_MANAGER",
    title: "Unit Global Owner / Ofis Sahibi",
    phone: "+90 532 000 10 02",
    avatarColor: "bg-blue-950",
    active: true,
    clientId: "client-unit-global",
  },
  {
    id: "consultant-1",
    name: "Kaan Öründü",
    email: "kaan@unitglobal.com",
    calendarEmail: "kaan@unitglobal.com",
    role: "CONSULTANT",
    title: "Gayrimenkul Danışmanı",
    phone: "+90 532 000 20 01",
    avatarColor: "bg-blue-900",
    active: true,
    clientId: "client-unit-global",
  },
];

export const clients: OfficeClient[] = [
  {
    id: "client-unit-global",
    name: "Unit Global",
    ownerName: "Dorukhan Öründü",
    inviteFromEmail: "mrtcnasln@gmail.com",
    userLimit: 5,
    status: "Hazır",
    logoUrl: UNIT_GLOBAL_LOGO_DATA_URL,
    createdAt: new Date(2026, 5, 11).toISOString(),
  },
];

const assignableUserIds = ["manager-1", "consultant-1"];
const consultantUserIds = ["consultant-1"];

const images = [
  "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1600573472591-ee6981cf35b6?auto=format&fit=crop&w=900&q=80",
];

const districts = [
  ["Beşiktaş", "Bebek"],
  ["Beşiktaş", "Etiler"],
  ["Şişli", "Nişantaşı"],
  ["Beşiktaş", "Levent"],
  ["Sarıyer", "Maslak"],
  ["Beşiktaş", "Ortaköy"],
  ["Eyüpsultan", "Göktürk"],
  ["Sarıyer", "Zekeriyaköy"],
  ["Kadıköy", "Caddebostan"],
  ["Kadıköy", "Suadiye"],
];

export const properties: Property[] = Array.from({ length: 15 }).map((_, index) => {
  const [district, neighborhood] = districts[index % districts.length];
  const consultantId = consultantUserIds[index % consultantUserIds.length];
  const price = [28500000, 42500000, 76000000, 18500000, 98000000][index % 5] + index * 850000;

  return {
    id: `property-${index + 1}`,
    title: `${neighborhood} ${index % 3 === 0 ? "Panoramik Boğaz Manzaralı" : index % 3 === 1 ? "Rezidans" : "Bahçeli Villa"} Portföy`,
    listingType: index % 4 === 0 ? "KIRALIK" : "SATILIK",
    price,
    currency: index % 4 === 0 ? "USD" : "TRY",
    city: "İstanbul",
    district,
    neighborhood,
    projectName: ["Unit Privé", "Bosphorus Line", "Noble Residence", "Atelier 34"][index % 4],
    squareMeters: 145 + index * 18,
    rooms: ["2+1", "3+1", "4+1", "5+2"][index % 4],
    floor: index % 2 === 0 ? "Ara kat" : "Bahçe dubleksi",
    buildingAge: `${index % 8} yıl`,
    furnished: index % 3 === 0,
    description: "Premium müşteri profili için hazırlanmış, güçlü lokasyon avantajı ve yüksek marka algısı taşıyan özel portföy.",
    features: ["Otopark", "Güvenlik", "Akıllı ev", "Teras", "Depo", "Sosyal alan"].slice(0, 3 + (index % 3)),
    coverImage: images[index % images.length],
    gallery: [images[index % images.length], images[(index + 1) % images.length], images[(index + 2) % images.length]],
    videoUrl: "https://unitglobal.example/video",
    listingUrl: "https://unitglobal.example/ilan",
    consultantId,
    status: ["AKTIF", "AKTIF", "OPSIYONLU", "PASIF", "SATILDI", "KIRALANDI"][index % 6] as Property["status"],
    createdAt: new Date(2026, 4, 8 + index).toISOString(),
  };
});

export const importedProperties: Property[] = [
  {
    id: "property-unitglobal-cl25-4",
    title: "Beşiktaş Kiralık Oda | Fully Furnished Room for Rent #CL25.4",
    listingType: "KIRALIK",
    price: 20900,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Beşiktaş",
    projectName: "Unit Global Portföy",
    squareMeters: 20,
    rooms: "Stüdyo (1+0)",
    floor: "",
    buildingAge: "",
    furnished: true,
    description: "Unit Global Sahibinden mağaza listesinden manuel eklenen kiralık oda portföyü. İlan tarihi: 11 Aralık 2025.",
    features: ["20.900 TL", "20 m²", "Stüdyo (1+0)", "Eşyalı"],
    coverImage: images[0],
    gallery: [images[0]],
    videoUrl: "",
    listingUrl: "https://unitglobal.sahibinden.com/",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/",
    externalId: "UNITGLOBAL-LIST-CL25-4",
    syncedAt: new Date(2025, 11, 11).toISOString(),
    syncStatus: "SYNCED",
    sourceType: "AUTHORIZED_PORTFOLIO",
    consultantId: "consultant-1",
    status: "AKTIF",
    createdAt: new Date(2025, 11, 11).toISOString(),
  },
  {
    id: "property-unitglobal-ortakoy-dereboyu",
    title: "Ortaköy Dereboyu Caddesi'nde bahçeli eşyalı müstakil ev",
    listingType: "KIRALIK",
    price: 160000,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Ortaköy",
    projectName: "Dereboyu Caddesi",
    squareMeters: 270,
    rooms: "5+1",
    floor: "Müstakil",
    buildingAge: "",
    furnished: true,
    description: "Unit Global Sahibinden mağaza listesinden manuel eklenen bahçeli, eşyalı müstakil kiralık ev. İlan tarihi: 10 Aralık 2025.",
    features: ["160.000 TL", "270 m²", "5+1", "Bahçeli", "Eşyalı"],
    coverImage: images[1],
    gallery: [images[1]],
    videoUrl: "",
    listingUrl: "https://unitglobal.sahibinden.com/",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/",
    externalId: "UNITGLOBAL-LIST-ORTAKOY-DEREBOYU",
    syncedAt: new Date(2025, 11, 10).toISOString(),
    syncStatus: "SYNCED",
    sourceType: "AUTHORIZED_PORTFOLIO",
    consultantId: "consultant-2",
    status: "AKTIF",
    createdAt: new Date(2025, 11, 10).toISOString(),
  },
  {
    id: "property-unitglobal-cl23-3",
    title: "Beşiktaş Kiralık Oda | Fully Furnished Room for Rent #CL23.3",
    listingType: "KIRALIK",
    price: 19400,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Beşiktaş",
    projectName: "Unit Global Portföy",
    squareMeters: 25,
    rooms: "Stüdyo (1+0)",
    floor: "",
    buildingAge: "",
    furnished: true,
    description: "Unit Global Sahibinden mağaza listesinden manuel eklenen kiralık oda portföyü. İlan tarihi: 11 Aralık 2025.",
    features: ["19.400 TL", "25 m²", "Stüdyo (1+0)", "Eşyalı"],
    coverImage: images[2],
    gallery: [images[2]],
    videoUrl: "",
    listingUrl: "https://unitglobal.sahibinden.com/",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/",
    externalId: "UNITGLOBAL-LIST-CL23-3",
    syncedAt: new Date(2025, 11, 11).toISOString(),
    syncStatus: "SYNCED",
    sourceType: "AUTHORIZED_PORTFOLIO",
    consultantId: "consultant-1",
    status: "AKTIF",
    createdAt: new Date(2025, 11, 11).toISOString(),
  },
  {
    id: "property-unitglobal-sisli-1-1",
    title: "Şişli | 1+1 | Eşyalı Kiralık Daire / Fully Furnished for Rent",
    listingType: "KIRALIK",
    price: 55000,
    currency: "TRY",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Şişli",
    projectName: "Unit Global Portföy",
    squareMeters: 83,
    rooms: "1+1",
    floor: "",
    buildingAge: "",
    furnished: true,
    description: "Unit Global Sahibinden mağaza listesinden manuel eklenen eşyalı 1+1 kiralık daire. İlan tarihi: 10 Aralık 2025.",
    features: ["55.000 TL", "83 m²", "1+1", "Eşyalı"],
    coverImage: images[3],
    gallery: [images[3]],
    videoUrl: "",
    listingUrl: "https://unitglobal.sahibinden.com/",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/",
    externalId: "UNITGLOBAL-LIST-SISLI-1-1",
    syncedAt: new Date(2025, 11, 10).toISOString(),
    syncStatus: "SYNCED",
    sourceType: "AUTHORIZED_PORTFOLIO",
    consultantId: "consultant-2",
    status: "AKTIF",
    createdAt: new Date(2025, 11, 10).toISOString(),
  },
];

export const importedComparables: MarketComparable[] = importedProperties.flatMap((property, propertyIndex) => {
  const sameDistrict = importedProperties.filter((item) => item.id !== property.id && item.district === property.district);
  const sample = sameDistrict.length ? sameDistrict : importedProperties.filter((item) => item.id !== property.id).slice(0, 3);

  return sample.slice(0, 3).map((item, index) => ({
    id: `unit-comp-${propertyIndex + 1}-${index + 1}`,
    propertyId: property.id,
    source: "Sahibinden",
    title: item.title,
    url: item.listingUrl,
    price: item.price,
    squareMeters: item.squareMeters,
    district: item.district,
    lastCheckedAt: new Date(2025, 11, 11).toISOString(),
    status: "AKTIF",
  }));
});

export const importedReports: MarketAnalysisReport[] = importedProperties.map((property, index) => {
  const rows = importedComparables.filter((item) => item.propertyId === property.id);
  const prices = rows.map((item) => item.price);
  const sqmPrices = rows.map((item) => Math.round(item.price / Math.max(item.squareMeters, 1)));
  const averagePrice = prices.length ? Math.round(prices.reduce((sum, item) => sum + item, 0) / prices.length) : property.price;
  const minPrice = prices.length ? Math.min(...prices) : property.price;
  const maxPrice = prices.length ? Math.max(...prices) : property.price;
  const averageSqmPrice = sqmPrices.length ? Math.round(sqmPrices.reduce((sum, item) => sum + item, 0) / sqmPrices.length) : Math.round(property.price / Math.max(property.squareMeters, 1));
  const pricePosition = property.price > maxPrice ? "Üst bantta" : property.price < minPrice ? "Alt bantta" : "Portföy bandında";

  return {
    id: `unit-report-${index + 1}`,
    propertyId: property.id,
    averagePrice,
    minPrice,
    maxPrice,
    averageSqmPrice,
    competitorCount: Math.max(rows.length, 1),
    pricePosition,
    suggestedMin: Math.round(property.price * 0.96),
    suggestedMax: Math.round(property.price * 1.04),
    consultantComment: "Bu analiz Unit Global mağaza listesinden manuel girilen portföy fiyatlarıyla çalışır. Yeni emsal verisi eklendikçe öneri aralığı daha netleşir.",
    createdAt: new Date(2025, 11, 11).toISOString(),
  };
});

export const importedPriceHistory: PriceHistory[] = importedProperties.flatMap((property, propertyIndex) =>
  [0.98, 1, 1].map((factor, index) => ({
    id: `unit-price-${propertyIndex + 1}-${index + 1}`,
    propertyId: property.id,
    price: Math.round(property.price * factor),
    date: new Date(2025, 9 + index, 11).toISOString(),
  }))
);

export const leads: Lead[] = Array.from({ length: 20 }).map((_, index) => ({
  id: `lead-${index + 1}`,
  name: [
    "Ayşe Demir",
    "Kemal Arıkan",
    "Zeynep Sönmez",
    "Murat Güner",
    "Elif Özkan",
    "Burak Şahin",
    "İdil Yalın",
    "Cem Uçar",
  ][index % 8],
  email: `lead${index + 1}@example.com`,
  phone: `+90 533 10${index.toString().padStart(2, "0")} ${index.toString().padStart(2, "0")} ${index.toString().padStart(2, "0")}`,
  source: ["Web Form", "Instagram", "Referans", "Telefon", "E-posta"][index % 5],
  budget: 15000000 + index * 1750000,
  interest: ["Bebek yalı dairesi", "Etiler rezidans", "Nişantaşı yatırım", "Zekeriyaköy villa"][index % 4],
  externalId: `M-${String(index + 1).padStart(4, "0")}`,
  address: ["Bebek, Beşiktaş", "Etiler, Beşiktaş", "Nişantaşı, Şişli", "Zekeriyaköy, Sarıyer"][index % 4],
  propertyOwner: ["Ayhan Yılmaz", "Derya Öz", "Selin Kaya", "Barış Aksoy"][index % 4],
  customerType: index % 3 === 0 ? "MULK_SAHIBI" : "KIRACI",
  status: ["YENI_LEAD", "ARANDI", "RANDEVU_ALINDI", "TEKLIF_VERILDI", "KAYBEDILDI"][index % 5] as Lead["status"],
  consultantId: consultantUserIds[index % consultantUserIds.length],
  notes: "Yüksek niyetli lead. İlk görüşme sonrası lokasyon ve ödeme planı netleştirilecek.",
  createdAt: new Date(2026, 4, 4 + index).toISOString(),
}));

export const starterLeads: Lead[] = [
  {
    id: "lead-starter-1",
    name: "No Name 01",
    email: "noname01@example.com",
    phone: "+90 5xx xxx xx xx",
    source: "Telefon",
    budget: 0,
    interest: "Kiralık 1+1",
    externalId: "M-0001",
    address: "Adres girilecek",
    propertyOwner: "Mülk sahibi girilecek",
    customerType: "KIRACI",
    status: "YENI_LEAD",
    consultantId: "consultant-1",
    notes: "Örnek müşteri kaydı. Detaylar görüşme sonrası girilecek.",
    createdAt: new Date(2026, 5, 9).toISOString(),
  },
  {
    id: "lead-starter-2",
    name: "No Name 02",
    email: "noname02@example.com",
    phone: "+90 5xx xxx xx xx",
    source: "WhatsApp",
    budget: 0,
    interest: "Caddebostan / Şişli kiralık",
    externalId: "M-0002",
    address: "Adres girilecek",
    propertyOwner: "Mülk sahibi girilecek",
    customerType: "KIRACI",
    status: "ARANDI",
    consultantId: "consultant-2",
    notes: "Örnek müşteri kaydı. Lokasyon alternatifi bekliyor.",
    createdAt: new Date(2026, 5, 9).toISOString(),
  },
  {
    id: "lead-starter-3",
    name: "No Name 03",
    email: "noname03@example.com",
    phone: "+90 5xx xxx xx xx",
    source: "Referans",
    budget: 0,
    interest: "Eşyalı 2+1 / 3+1",
    externalId: "M-0003",
    address: "Adres girilecek",
    propertyOwner: "Mülk sahibi girilecek",
    customerType: "MULK_SAHIBI",
    status: "YENI_LEAD",
    consultantId: "consultant-1",
    notes: "Örnek müşteri kaydı. Bütçe netleşecek.",
    createdAt: new Date(2026, 5, 9).toISOString(),
  },
];

export const leadActions: LeadAction[] = leads.slice(0, 12).map((lead, index) => ({
  id: `lead-action-${index + 1}`,
  leadId: lead.id,
  userId: lead.consultantId,
  action: ["Arama", "WhatsApp", "Portföy paylaşımı", "Randevu planlama"][index % 4],
  note: "Lead ile temas kuruldu, uygun portföyler paylaşıldı.",
  createdAt: new Date(2026, 4, 10 + index).toISOString(),
}));

export const starterLeadActions: LeadAction[] = starterLeads.map((lead, index) => ({
  id: `starter-lead-action-${index + 1}`,
  leadId: lead.id,
  userId: lead.consultantId,
  action: ["Arama", "WhatsApp", "Randevu planlama"][index % 3],
  note: "İlk temas notu eklendi, uygun portföyler kontrol edilecek.",
  createdAt: new Date(2026, 5, 9 + index).toISOString(),
}));

export const tasks: Task[] = Array.from({ length: 20 }).map((_, index) => ({
  id: `task-${index + 1}`,
  title: [
    "Bölge fiyatlarını kontrol et",
    "Portföy fotoğraf seçimini onayla",
    "Lead takip araması yap",
    "Sahibinden sync durumunu kontrol et",
    "Satıcı raporunu güncelle",
  ][index % 5],
  description: "Gün içinde tamamlanması gereken operasyon aksiyonu.",
  dueDate: new Date(2026, 5, 9 + (index % 8)).toISOString(),
  priority: ["YUKSEK", "ORTA", "DUSUK"][index % 3] as Task["priority"],
  status: ["ACIK", "DEVAM", "TAMAMLANDI"][index % 3] as Task["status"],
  type: ["ARAMA", "RANDEVU", "YER_GOSTERIMI", "EVRAK_TAKIBI", "FOTOGRAF_CEKIMI", "FIYAT_GUNCELLEME", "MUSTERI_TAKIBI"][index % 7] as Task["type"],
  assignedToId: assignableUserIds[index % assignableUserIds.length],
  createdById: "admin-1",
  leadId: starterLeads[index % starterLeads.length]?.id,
  propertyId: importedProperties[index % importedProperties.length]?.id,
}));

export const notifications: Notification[] = Array.from({ length: 14 }).map((_, index) => ({
  id: `notification-${index + 1}`,
  title: ["Yeni lead atandı", "Piyasa analizi güncellendi", "Görev son tarihi yaklaştı", "Portföy durumu değişti"][index % 4],
  message: "Unit Global operasyon panelinde yeni bir aksiyon bekliyor.",
  targetUserId: index % 3 === 0 ? undefined : assignableUserIds[index % assignableUserIds.length],
  status: index % 2 === 0 ? "OKUNMADI" : "OKUNDU",
  createdAt: new Date(2026, 5, 1 + index).toISOString(),
}));

export const comparables: MarketComparable[] = properties.flatMap((property, propertyIndex) =>
  Array.from({ length: 3 }).map((_, index) => ({
    id: `comp-${propertyIndex + 1}-${index + 1}`,
    propertyId: property.id,
    source: ["Sahibinden", "Hepsiemlak", "Emlakjet"][index] as MarketComparable["source"],
    title: `${property.neighborhood} emsal kayıt ${index + 1}`,
    url: `https://example.com/emsal-${propertyIndex + 1}-${index + 1}`,
    price: Math.round(property.price * (0.92 + index * 0.05)),
    squareMeters: property.squareMeters + index * 12,
    district: property.district,
    lastCheckedAt: new Date(2026, 5, 5 + index).toISOString(),
    status: ["AKTIF", "FIYAT_DEGISTI", "AKTIF"][index] as MarketComparable["status"],
  }))
);

export const reports: MarketAnalysisReport[] = properties.map((property, index) => ({
  id: `report-${index + 1}`,
  propertyId: property.id,
  averagePrice: Math.round(property.price * 0.97),
  minPrice: Math.round(property.price * 0.86),
  maxPrice: Math.round(property.price * 1.12),
  averageSqmPrice: Math.round((property.price / property.squareMeters) * 0.96),
  competitorCount: 8 + (index % 7),
  pricePosition: index % 3 === 0 ? "Piyasanın üst bandında" : index % 3 === 1 ? "Rekabetçi aralıkta" : "Araştırma gerekli",
  suggestedMin: Math.round(property.price * 0.94),
  suggestedMax: Math.round(property.price * 1.04),
  consultantComment: "Portföy güçlü lokasyonda. Bölgedeki yeni kayıtlar eklendikçe fiyat görünümü daha net okunur.",
  createdAt: new Date(2026, 5, 6).toISOString(),
}));

export const priceHistory: PriceHistory[] = properties.flatMap((property, propertyIndex) =>
  Array.from({ length: 4 }).map((_, index) => ({
    id: `price-${propertyIndex + 1}-${index + 1}`,
    propertyId: property.id,
    price: Math.round(property.price * (1 - (3 - index) * 0.018)),
    date: new Date(2026, index + 1, 12).toISOString(),
  }))
);

export const activityLogs: ActivityLog[] = Array.from({ length: 18 }).map((_, index) => ({
  id: `activity-${index + 1}`,
  userId: users[index % users.length].id,
  action: ["Portföy güncellendi", "Lead aksiyonu eklendi", "Görev tamamlandı", "Bildirim gönderildi"][index % 4],
  entity: ["Property", "Lead", "Task", "Notification"][index % 4],
  createdAt: new Date(2026, 5, 2 + index).toISOString(),
}));

export const documents: DocumentRecord[] = [
  {
    id: "doc-1",
    title: "Ortaköy Yetki Belgesi",
    type: "YETKI_BELGESI",
    relatedType: "PROPERTY",
    relatedId: "property-unitglobal-ortakoy-dereboyu",
    assignedToId: "manager-1",
    status: "TAMAM",
    uploadedAt: new Date(2026, 5, 3).toISOString(),
  },
  {
    id: "doc-2",
    title: "Şişli Kimlik Kontrolü",
    type: "KIMLIK",
    relatedType: "PROPERTY",
    relatedId: "property-unitglobal-sisli-1-1",
    assignedToId: "manager-1",
    status: "BEKLIYOR",
    uploadedAt: new Date(2026, 5, 5).toISOString(),
  },
  {
    id: "doc-3",
    title: "No Name 01 Randevu Formu",
    type: "DEGERLEME",
    relatedType: "LEAD",
    relatedId: "lead-starter-1",
    assignedToId: "consultant-1",
    status: "EKSIK",
    uploadedAt: new Date(2026, 5, 6).toISOString(),
  },
  {
    id: "doc-4",
    title: "Beşiktaş Kira Sözleşmesi Taslağı",
    type: "KIRA_SOZLESMESI",
    relatedType: "PROPERTY",
    relatedId: "property-unitglobal-cl25-4",
    assignedToId: "manager-1",
    status: "BEKLIYOR",
    uploadedAt: new Date(2026, 5, 7).toISOString(),
  },
];

export const marketListings: MarketListing[] = [
  {
    id: "market-sahibinden-etiler-1",
    source: "Sahibinden",
    title: "Etiler Nispetiye Caddesi premium rezidans 2+1",
    url: "https://www.sahibinden.com/demo/unit-global-market-etiler-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Etiler",
    street: "Nispetiye Caddesi",
    listingType: "KIRALIK",
    price: 145000,
    currency: "TRY",
    squareMeters: 115,
    rooms: "2+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 3).toISOString(),
  },
  {
    id: "market-hepsiemlak-etiler-1",
    source: "Hepsiemlak",
    title: "Etiler Nispetiye özel güvenlikli sitede 3+1",
    url: "https://www.hepsiemlak.com/demo/unit-global-market-etiler-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Etiler",
    street: "Nispetiye Caddesi",
    listingType: "KIRALIK",
    price: 172000,
    currency: "TRY",
    squareMeters: 155,
    rooms: "3+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 4).toISOString(),
  },
  {
    id: "market-emlakjet-etiler-1",
    source: "Emlakjet",
    title: "Etiler Nispetiye modern eşyalı 1+1",
    url: "https://www.emlakjet.com/demo/unit-global-market-etiler-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Etiler",
    street: "Nispetiye Caddesi",
    listingType: "KIRALIK",
    price: 98000,
    currency: "TRY",
    squareMeters: 72,
    rooms: "1+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 5).toISOString(),
  },
  {
    id: "market-sahibinden-bebek-1",
    source: "Sahibinden",
    title: "Bebek Cevdet Paşa Caddesi Boğaz manzaralı 3+1",
    url: "https://www.sahibinden.com/demo/unit-global-market-bebek-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Bebek",
    street: "Cevdet Paşa Caddesi",
    listingType: "KIRALIK",
    price: 285000,
    currency: "TRY",
    squareMeters: 190,
    rooms: "3+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 5).toISOString(),
  },
  {
    id: "market-hepsiemlak-bebek-1",
    source: "Hepsiemlak",
    title: "Bebek Cevdet Paşa yenilenmiş lüks daire",
    url: "https://www.hepsiemlak.com/demo/unit-global-market-bebek-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Bebek",
    street: "Cevdet Paşa Caddesi",
    listingType: "KIRALIK",
    price: 245000,
    currency: "TRY",
    squareMeters: 165,
    rooms: "3+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 6).toISOString(),
  },
  {
    id: "market-emlakjet-bebek-1",
    source: "Emlakjet",
    title: "Bebek Cevdet Paşa teraslı dubleks",
    url: "https://www.emlakjet.com/demo/unit-global-market-bebek-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Bebek",
    street: "Cevdet Paşa Caddesi",
    listingType: "SATILIK",
    price: 128000000,
    currency: "TRY",
    squareMeters: 260,
    rooms: "4+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 6).toISOString(),
  },
  {
    id: "market-sahibinden-nisantasi-1",
    source: "Sahibinden",
    title: "Nişantaşı Teşvikiye prestijli binada 2+1",
    url: "https://www.sahibinden.com/demo/unit-global-market-nisantasi-1",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Nişantaşı",
    street: "Teşvikiye Caddesi",
    listingType: "KIRALIK",
    price: 138000,
    currency: "TRY",
    squareMeters: 110,
    rooms: "2+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 7).toISOString(),
  },
  {
    id: "market-hepsiemlak-nisantasi-1",
    source: "Hepsiemlak",
    title: "Nişantaşı Abdi İpekçi çevresi tasarım daire",
    url: "https://www.hepsiemlak.com/demo/unit-global-market-nisantasi-1",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Nişantaşı",
    street: "Abdi İpekçi Caddesi",
    listingType: "KIRALIK",
    price: 210000,
    currency: "TRY",
    squareMeters: 145,
    rooms: "3+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 7).toISOString(),
  },
  {
    id: "market-emlakjet-levent-1",
    source: "Emlakjet",
    title: "Levent Büyükdere aksında rezidans 2+1",
    url: "https://www.emlakjet.com/demo/unit-global-market-levent-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Levent",
    street: "Büyükdere Caddesi",
    listingType: "KIRALIK",
    price: 128000,
    currency: "TRY",
    squareMeters: 98,
    rooms: "2+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 8).toISOString(),
  },
  {
    id: "market-hepsiemlak-levent-1",
    source: "Hepsiemlak",
    title: "Levent Büyükdere yakınında satılık lüks rezidans",
    url: "https://www.hepsiemlak.com/demo/unit-global-market-levent-1",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Levent",
    street: "Büyükdere Caddesi",
    listingType: "SATILIK",
    price: 56000000,
    currency: "TRY",
    squareMeters: 180,
    rooms: "3+1",
    status: "AKTIF",
    listedAt: new Date(2026, 5, 8).toISOString(),
  },
];

export const initialData: CrmData = {
  clients,
  users,
  properties: [],
  leads: [],
  leadActions: [],
  tasks: [],
  documents: [],
  notifications: [],
  comparables: [],
  marketListings: [],
  reports: [],
  priceHistory: [],
  activityLogs: [],
  setting: {
    companyName: "Unit Global",
    defaultCurrency: "TRY",
    leadSlaHours: 24,
    notificationEmail: "mertcan@unitcrm.com",
  },
};
