import type { ListingProvider, ProviderListing } from "./listing-provider";

const demoListings: ProviderListing[] = [
  {
    externalId: "UG-SHB-ETILER-001",
    title: "Etiler'de yüksek kat premium rezidans 2+1",
    listingType: "KIRALIK",
    price: 145000,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Etiler",
    projectName: "Etiler Premium Residence",
    squareMeters: 135,
    rooms: "2+1",
    floor: "Yüksek kat",
    buildingAge: "0-5 yıl",
    furnished: true,
    description: "Unit Global yetkili portföy demo kaydı. Premium rezidans, yüksek kat, eşyalı ve şehir manzaralı.",
    features: ["Sahibinden demo sync", "Yetkili portföy", "Eşyalı", "Yüksek kat", "Rezidans"],
    coverImage: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80",
    gallery: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"],
    videoUrl: "",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/demo/UG-SHB-ETILER-001",
    sourceType: "AUTHORIZED_PORTFOLIO",
    status: "AKTIF",
  },
  {
    externalId: "UG-SHB-BEBEK-002",
    title: "Bebek'te Boğaz hattında satılık lüks daire",
    listingType: "SATILIK",
    price: 68500000,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Bebek",
    projectName: "Bebek Bosphorus Line",
    squareMeters: 210,
    rooms: "3+1",
    floor: "Ara kat",
    buildingAge: "6-10 yıl",
    furnished: false,
    description: "Unit Global kurumsal mağaza demo kaydı. Boğaz hattına yakın, geniş planlı premium satılık daire.",
    features: ["Sahibinden demo sync", "Kurumsal mağaza", "Boğaz hattı", "3+1", "Satılık"],
    coverImage: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80",
    gallery: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80"],
    videoUrl: "",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/demo/UG-SHB-BEBEK-002",
    sourceType: "OWN_LISTING",
    status: "AKTIF",
  },
  {
    externalId: "UG-SHB-NISANTASI-003",
    title: "Nişantaşı'nda concierge hizmetli 1+1 kiralık daire",
    listingType: "KIRALIK",
    price: 92000,
    currency: "TRY",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Nişantaşı",
    projectName: "Nişantaşı Suites",
    squareMeters: 78,
    rooms: "1+1",
    floor: "Ara kat",
    buildingAge: "0-5 yıl",
    furnished: true,
    description: "Unit Global yetkili portföy demo kaydı. Nişantaşı merkezde, concierge hizmetli, eşyalı kiralık daire.",
    features: ["Sahibinden demo sync", "Yetkili portföy", "Concierge", "Eşyalı", "1+1"],
    coverImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",
    gallery: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80"],
    videoUrl: "",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/demo/UG-SHB-NISANTASI-003",
    sourceType: "AUTHORIZED_PORTFOLIO",
    status: "AKTIF",
  },
  {
    externalId: "UG-SHB-LEVENT-004",
    title: "Levent'te özel bahçeli premium villa",
    listingType: "SATILIK",
    price: 124000000,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Levent",
    projectName: "Levent Private Villas",
    squareMeters: 360,
    rooms: "5+2",
    floor: "Villa",
    buildingAge: "0-5 yıl",
    furnished: false,
    description: "Unit Global kurumsal mağaza demo kaydı. Levent'te özel bahçeli, geniş metrekareli premium villa.",
    features: ["Sahibinden demo sync", "Kurumsal mağaza", "Villa", "Özel bahçe", "Satılık"],
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80",
    gallery: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80"],
    videoUrl: "",
    sourcePlatform: "Sahibinden",
    sourceUrl: "https://unitglobal.sahibinden.com/demo/UG-SHB-LEVENT-004",
    sourceType: "OWN_LISTING",
    status: "AKTIF",
  },
  {
    externalId: "UG-EMJ-ETILER-005",
    title: "Emlakjet demo | Etiler'de bahçe teraslı 3+1",
    listingType: "KIRALIK",
    price: 175000,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Etiler",
    projectName: "Etiler Garden Suites",
    squareMeters: 165,
    rooms: "3+1",
    floor: "Bahçe dubleksi",
    buildingAge: "0-5 yıl",
    furnished: true,
    description: "Emlakjet benzeri kaynak için demo kayıt. Veri manuel/izinli sağlayıcı modunda tutulur.",
    features: ["Emlakjet demo", "Yetkili portföy", "Bahçe terası", "3+1"],
    coverImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80",
    gallery: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80"],
    videoUrl: "",
    sourcePlatform: "Emlakjet",
    sourceUrl: "https://unitglobal.example/emlakjet-demo/UG-EMJ-ETILER-005",
    sourceType: "AUTHORIZED_PORTFOLIO",
    status: "AKTIF",
  },
  {
    externalId: "UG-HUR-NISANTASI-006",
    title: "Hürriyet Emlak demo | Nişantaşı'nda satılık residence",
    listingType: "SATILIK",
    price: 54000000,
    currency: "TRY",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Nişantaşı",
    projectName: "Nişantaşı Residence",
    squareMeters: 155,
    rooms: "2+1",
    floor: "Ara kat",
    buildingAge: "0-5 yıl",
    furnished: false,
    description: "Hürriyet Emlak benzeri kaynak için demo kayıt. Genel ilan çekimi yapmaz.",
    features: ["Hürriyet Emlak demo", "Kurumsal portföy", "Residence", "Satılık"],
    coverImage: "https://images.unsplash.com/photo-1600573472591-ee6981cf35b6?auto=format&fit=crop&w=900&q=80",
    gallery: ["https://images.unsplash.com/photo-1600573472591-ee6981cf35b6?auto=format&fit=crop&w=900&q=80"],
    videoUrl: "",
    sourcePlatform: "Hürriyet Emlak",
    sourceUrl: "https://unitglobal.example/hurriyet-demo/UG-HUR-NISANTASI-006",
    sourceType: "OWN_LISTING",
    status: "AKTIF",
  },
  {
    externalId: "UG-HEP-LEVENT-007",
    title: "Hepsiemlak demo | Levent'te yüksek kat 2+1 rezidans",
    listingType: "KIRALIK",
    price: 120000,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Levent",
    projectName: "Levent Tower",
    squareMeters: 118,
    rooms: "2+1",
    floor: "Yüksek kat",
    buildingAge: "0-5 yıl",
    furnished: true,
    description: "Hepsiemlak benzeri kaynak için demo kayıt. Veri sadece demo/izinli portföy kapsamındadır.",
    features: ["Hepsiemlak demo", "Yetkili portföy", "Yüksek kat", "Eşyalı"],
    coverImage: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80",
    gallery: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"],
    videoUrl: "",
    sourcePlatform: "Hepsiemlak",
    sourceUrl: "https://unitglobal.example/hepsiemlak-demo/UG-HEP-LEVENT-007",
    sourceType: "AUTHORIZED_PORTFOLIO",
    status: "AKTIF",
  },
];

export const sahibindenDemoProvider: ListingProvider = {
  async fetchOwnListings() {
    return demoListings;
  },
  normalizeListing(listing, consultantId, syncedAt) {
    return {
      ...listing,
      id: `property-${listing.externalId.toLowerCase()}`,
      listingUrl: listing.sourceUrl,
      sourcePlatform: listing.sourcePlatform,
      syncStatus: "SYNCED",
      consultantId,
      syncedAt,
      createdAt: syncedAt,
    };
  },
  async syncListings(currentProperties, consultantId) {
    const syncedAt = new Date().toISOString();
    const listings = await this.fetchOwnListings();
    const existingUrls = new Set(currentProperties.map((property) => property.sourceUrl ?? property.listingUrl).filter(Boolean));
    const added = listings
      .filter((listing) => !existingUrls.has(listing.sourceUrl))
      .map((listing) => this.normalizeListing(listing, consultantId, syncedAt));

    return {
      provider: "Sahibinden",
      added,
      skipped: listings.length - added.length,
      syncedAt,
    };
  },
};
